openapi: 3.0.0
info:
  title: Sample API for Schemathesis
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Simple Ping Endpoint
      operationId: pingGet
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: pong
