openapi: 3.0.2
info:
  title: Simple Employee List API
  version: 1.0.0
  description: An extremely basic API to list employees.
servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /users:
    get:
      summary: Get a list of employees
      operationId: listEmployees
      tags:
        - Employees
      responses:
        '200':
          description: A list of employees with name and department.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SimpleEmployee'
    post:
      summary: Create a new employee
      operationId: createEmployee
      tags:
        - Employees
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimpleEmployee'
      responses:
        '201':
          description: Employee created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleEmployee'
        '400':
          description: Invalid input data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    SimpleEmployee:
      type: object
      required:
        - name
        - department
      properties:
        name:
          type: string
          description: Employee's name.
          example: Taro Yamada
        department:
          type: string
          description: Employee's department.
          example: Sales
    Error:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: A message describing the error.
          example: Invalid input data provided.